/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Home: () => import('#controllers/home_controller'),
  ImportMyanimelist: () => import('#controllers/import_myanimelist_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Watchlist: () => import('#controllers/watchlist_controller'),
}
