/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnimeGenreSchema extends BaseModel {
  static $columns = ['animeId', 'genreId', 'id'] as const
  $columns = AnimeGenreSchema.$columns
  @column()
  declare animeId: number | null
  @column()
  declare genreId: number | null
  @column({ isPrimary: true })
  declare id: number
}

export class AnimeSchema extends BaseModel {
  static $columns = [
    'alternativeTitles',
    'backgroundUrl',
    'createdAt',
    'episodesCount',
    'externalSource',
    'externalSourceId',
    'id',
    'myanimelistId',
    'nsfw',
    'releasedAt',
    'score',
    'season',
    'seasonYear',
    'status',
    'synopsis',
    'thumbnailUrl',
    'title',
    'trailerId',
    'trailerSource',
    'type',
    'updatedAt',
  ] as const
  $columns = AnimeSchema.$columns
  @column()
  declare alternativeTitles: string | null
  @column()
  declare backgroundUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare episodesCount: number | null
  @column()
  declare externalSource: string | null
  @column()
  declare externalSourceId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare myanimelistId: string | null
  @column()
  declare nsfw: boolean
  @column.dateTime()
  declare releasedAt: DateTime
  @column()
  declare score: number | null
  @column()
  declare season: string | null
  @column()
  declare seasonYear: number | null
  @column()
  declare status: string | null
  @column()
  declare synopsis: string | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare title: string
  @column()
  declare trailerId: string | null
  @column()
  declare trailerSource: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GenreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = GenreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare slug: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MovieGenreSchema extends BaseModel {
  static $columns = ['genreId', 'id', 'movieId'] as const
  $columns = MovieGenreSchema.$columns
  @column()
  declare genreId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movieId: number | null
}

export class MovieSchema extends BaseModel {
  static $columns = [
    'alternativeTitles',
    'createdAt',
    'externalSource',
    'externalSourceId',
    'id',
    'nsfw',
    'releasedAt',
    'score',
    'status',
    'synopsis',
    'thumbnailUrl',
    'title',
    'tmdbId',
    'updatedAt',
  ] as const
  $columns = MovieSchema.$columns
  @column()
  declare alternativeTitles: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalSource: string | null
  @column()
  declare externalSourceId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nsfw: boolean
  @column.date()
  declare releasedAt: DateTime
  @column()
  declare score: number | null
  @column()
  declare status: string | null
  @column()
  declare synopsis: string | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare title: string
  @column()
  declare tmdbId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TvshowGenreSchema extends BaseModel {
  static $columns = ['genreId', 'id', 'tvshowId'] as const
  $columns = TvshowGenreSchema.$columns
  @column()
  declare genreId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tvshowId: number | null
}

export class TvshowSchema extends BaseModel {
  static $columns = [
    'alternativeTitles',
    'createdAt',
    'externalSource',
    'externalSourceId',
    'id',
    'nsfw',
    'numberOfEpisodes',
    'numberOfSeasons',
    'releasedAt',
    'score',
    'status',
    'synopsis',
    'thumbnailUrl',
    'title',
    'tmdbId',
    'updatedAt',
  ] as const
  $columns = TvshowSchema.$columns
  @column()
  declare alternativeTitles: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalSource: string | null
  @column()
  declare externalSourceId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nsfw: boolean
  @column()
  declare numberOfEpisodes: number | null
  @column()
  declare numberOfSeasons: number | null
  @column.date()
  declare releasedAt: DateTime
  @column()
  declare score: number | null
  @column()
  declare status: string | null
  @column()
  declare synopsis: string | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare title: string
  @column()
  declare tmdbId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserAnimeSchema extends BaseModel {
  static $columns = [
    'animeId',
    'createdAt',
    'currentEpisode',
    'id',
    'updatedAt',
    'userId',
    'watchStatus',
  ] as const
  $columns = UserAnimeSchema.$columns
  @column()
  declare animeId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentEpisode: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare watchStatus: string
}

export class UserMovieSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'movieId', 'updatedAt', 'userId', 'watchStatus'] as const
  $columns = UserMovieSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movieId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare watchStatus: string
}

export class UserTvshowSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'currentEpisode',
    'id',
    'tvshowId',
    'updatedAt',
    'userId',
    'watchStatus',
  ] as const
  $columns = UserTvshowSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare currentEpisode: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tvshowId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare watchStatus: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
